### ISSUE TITLE
macOS binary having wrong PATH?

### ISSUE THREAD

**Issue by thistehneisen** [marcelja/facebook-delete#39] opened 2021-10-30 07:11 UTC
```
➜  facebook-delete git:(master) ✗ ./deleter-macos
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
main.(*fbLogin).StoreProfileID(0xc000126480, {0xc0003fc000, 0x135ac46})
	/Users/marcel/pr/facebook-delete/deleter.go:178 +0xbe
main.(*fbLogin).IsLoggedIn(0xc000126480)
	/Users/marcel/pr/facebook-delete/deleter.go:172 +0x75
main.newFbLogin(0xc00010b140)
	/Users/marcel/pr/facebook-delete/deleter.go:113 +0x53
main.main()
	/Users/marcel/pr/facebook-delete/deleter.go:522 +0x289
```

Latest deleted-macos binary.

**Comment by thistehneisen** [comment] 2021-10-30 07:12
(My user is not marcel, neither path is `/Users/marcel/pr/facebook-delete/`)

**Comment by marcelja** [comment] 2021-10-30 07:47
duplicate of #38

The login process fails.
The path is not an issue. It's because I compiled the binaries from this system path.

**Closed by marcelja** 2021-10-30 07:47 UTC
